### ISSUE TITLE
Atbash is a cypher not just reversing letters

### ISSUE THREAD

**Issue by ThatChapThere** [markdoughty/CMP1903M-Workshop-Code#1]
The atbash cypher is when the alphabet is reversed, i.e. a=z, b=y e.t.c., not just reversing the order of letters.

**Comment by markdoughty** [comment]
Good point! This is a simplified version of Atbash - however, if you want to implement a full Atbash then please do!

**Comment by ThatChapThere** [comment]
Cool! I'll give it a go.
